// Pricing
export const M_SET_PRICING = "M_SET_PRICING";
export const M_SET_NAMES = "M_SET_NAMES";

//Cart
export const M_ADD_TO_CART = "M_ADD_TO_CART";
export const M_REMOVE_CART_ITEM = "M_REMOVE_CART_ITEM";
export const M_CHANGE_INPUT_QUANTITY = "M_CHANGE_INPUT_QUANTITY";
export const M_CHANGE_CURRENCY_RATIO = "M_CHANGE_CURRENCY_RATIO";
